name: Functionality Request
description: Request a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the information below.

  - type: input
    id: title
    attributes:
      label: Feature Title
      description: Provide a concise title for the feature you are requesting.
      placeholder: e.g., Add support for XYZ
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature or enhancement you would like to see.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific use case or scenario where this feature would be beneficial.
      placeholder: For example, when I want to...
    validations:
      required: true
